name: rocket_repository
description: A Dart class which exposes methods to implement rocket-related functionality.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  spacex_api:
    path: ../spacex_api

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.1
