name: rocket_repository
description: A Dart class which exposes methods to implement rocket-related functionality.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  spacex_api:
    # See spacex_demo repository's pubspec.yaml for more info
    # path: ../spacex_api
    git:
      url: https://github.com/yshean/spacex_api.git
      ref: main

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.1
